-- Source OLTP schema. Small on purpose. Every table here has to earn its place by
-- producing a change shape the consumer will have to handle.
--
-- customer      slowly changing, updates dominate
-- product       price churn, and a soft deactivate rather than a delete
-- order_header  status transitions, which is the update-heavy path
-- order_item    composite primary key, and the only table that gets hard deleted

create schema if not exists shop;

-- The load generator needs unique emails and skus across every run, not just within one.
-- Deriving that counter from max(customer_id) looks right and is not, because the customer
-- and product identity sequences advance independently and the names come off one counter.
-- A sequence in the database is the only place that fact can live without being re-derived.
create sequence shop.load_label_seq;

create table shop.customer (
    customer_id bigint generated by default as identity primary key,
    email       text        not null unique,
    full_name   text        not null,
    country     char(2)     not null,
    created_at  timestamptz not null default now(),
    updated_at  timestamptz not null default now()
);

create table shop.product (
    product_id  bigint generated by default as identity primary key,
    sku         text        not null unique,
    name        text        not null,
    price_cents integer     not null check (price_cents >= 0),
    active      boolean     not null default true,
    updated_at  timestamptz not null default now()
);

create table shop.order_header (
    order_id    bigint generated by default as identity primary key,
    customer_id bigint      not null references shop.customer,
    status      text        not null check (status in ('pending', 'paid', 'shipped', 'cancelled')),
    total_cents integer     not null default 0,
    placed_at   timestamptz not null default now(),
    updated_at  timestamptz not null default now()
);

-- Composite key on purpose. A merge keyed on a single surrogate column is the easy case
-- and it is not the case a real warehouse sync hits.
create table shop.order_item (
    order_id   bigint   not null references shop.order_header on delete cascade,
    line_no    smallint not null,
    product_id bigint   not null references shop.product,
    qty        smallint not null check (qty > 0),
    unit_cents integer  not null,
    primary key (order_id, line_no)
);

create index on shop.order_header (customer_id);
create index on shop.order_item (product_id);

-- Postgres 14 has no FOR ALL TABLES IN SCHEMA, that landed in 15. The list is explicit and
-- a table added later has to be added here too. A publication that silently misses a table
-- is a change stream that silently misses a table.
create publication cdc_shop
    for table shop.customer, shop.product, shop.order_header, shop.order_item;
